# Generated by Django 5.0.4 on 2024-05-13 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMCompanies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opened', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('address_legals', models.TextField(blank=True, null=True)),
                ('banking_details', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('company_type', models.IntegerField(blank=True, null=True)),
                ('industry', models.IntegerField(blank=True, null=True)),
                ('revenue', models.BigIntegerField(blank=True, null=True)),
                ('currency_id', models.IntegerField(blank=True, null=True)),
                ('employees', models.IntegerField(blank=True, null=True)),
                ('lead_id', models.IntegerField(blank=True, null=True)),
                ('webform_id', models.IntegerField(blank=True, null=True)),
                ('originator_id', models.IntegerField(blank=True, null=True)),
                ('origin_id', models.IntegerField(blank=True, null=True)),
                ('origin_version', models.IntegerField(blank=True, null=True)),
                ('has_phone', models.BooleanField(default=False)),
                ('has_email', models.BooleanField(default=False)),
                ('has_imol', models.BooleanField(default=False)),
                ('search_content', models.TextField(blank=True, null=True)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('last_activity_time', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies_created', to=settings.AUTH_USER_MODEL)),
                ('last_activity_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies_last_activity_by', to=settings.AUTH_USER_MODEL)),
                ('modify_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company (Owner)',
                'verbose_name_plural': 'Companies (Owners)',
                'db_table': 'crm_companies',
            },
        ),
        migrations.CreateModel(
            name='CRMContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opened', models.BooleanField(blank=True, null=True)),
                ('company_id', models.BigIntegerField(blank=True, null=True)),
                ('source_id', models.BooleanField(blank=True, null=True)),
                ('source_description', models.TextField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('second_name', models.CharField(blank=True, max_length=255, null=True)),
                ('post', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('lead_id', models.BigIntegerField(blank=True, null=True)),
                ('export', models.BooleanField(blank=True, null=True)),
                ('type_id', models.BigIntegerField(blank=True, null=True)),
                ('originator_id', models.BigIntegerField(blank=True, null=True)),
                ('origin_id', models.BigIntegerField(blank=True, null=True)),
                ('origin_version', models.BigIntegerField(blank=True, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('search_content', models.TextField(blank=True, null=True)),
                ('category_id', models.BigIntegerField(blank=True, null=True)),
                ('last_activity_time', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contacts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_contacts', to=settings.AUTH_USER_MODEL)),
                ('last_activity_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_activity_contacts', to=settings.AUTH_USER_MODEL)),
                ('modify_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact (Driver)',
                'verbose_name_plural': 'Contacts (Drivers)',
                'db_table': 'crm_contacts',
            },
        ),
        migrations.CreateModel(
            name='CRMContactDriverEC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opened', models.BooleanField(default=False)),
                ('ec_name', models.CharField(max_length=255)),
                ('ec_phone', models.CharField(max_length=50)),
                ('ec_email', models.EmailField(max_length=254)),
                ('relationship', models.CharField(max_length=100)),
                ('assigned_by_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crmcontactdriverec_assigned', to=settings.AUTH_USER_MODEL)),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_ec_contacts', to='contact.crmcontact')),
                ('created_by_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crmcontactdriverec_created', to=settings.AUTH_USER_MODEL)),
                ('modify_by_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crmcontactdriverec_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Driver Emergency Contact',
                'verbose_name_plural': 'Drivers Emergency Contact',
                'db_table': 'crm_contact_driver_ec',
            },
        ),
        migrations.CreateModel(
            name='CRMContactDrivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_content', models.TextField(blank=True, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('NEW', 'New'), ('Approve', 'Approve'), ('Decline', 'Decline')], max_length=255, null=True)),
                ('licence_type', models.CharField(blank=True, max_length=255, null=True)),
                ('licence_number', models.CharField(blank=True, max_length=255, null=True)),
                ('licence_state', models.CharField(blank=True, max_length=15, null=True)),
                ('expiration', models.DateField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_drivers', to=settings.AUTH_USER_MODEL)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_drivers', to='contact.crmcontact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_contact_drivers', to=settings.AUTH_USER_MODEL)),
                ('modify_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_contact_drivers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Driver Information',
                'verbose_name_plural': 'Drivers Information',
                'db_table': 'crm_contact_drivers',
            },
        ),
        migrations.CreateModel(
            name='CRMContactFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.CharField(blank=True, choices=[('Phone', 'Phone'), ('Email', 'Email')], max_length=255, null=True)),
                ('value_type', models.CharField(blank=True, default='WORK', max_length=255, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_fields', to='contact.crmcontact')),
            ],
            options={
                'db_table': 'crm_contact_fields',
            },
        ),
        migrations.CreateModel(
            name='CRMContactCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_by', models.SmallIntegerField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_relations', to='contact.crmcompanies')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_relations', to='contact.crmcontact')),
            ],
            options={
                'db_table': 'crm_contact_company_relations',
                'unique_together': {('contact', 'company')},
            },
        ),
    ]
