apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.global.namespace }}
  name: {{ .Values.containerName }}-config
data:
  DEBUG_MODE: "{{ .Values.config.debug }}"
  ORIGINAL: "{{ .Values.config.originHost }}"

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.global.namespace }}
  name: {{ .Values.containerName }}-nginx-config
data:
  nginx.conf: |
    server {
      listen 8080;
      server_name localhost;

      location /static/ {
        alias /usr/share/nginx/html/static/;
      }

      location / {
        proxy_pass http://localhost:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
    }
