apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: {{ .Values.global.namespace }}
  name: {{ .Values.name }}-hpa
  labels:
    app: {{ .Values.appLabel }}-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.name }}-deployment
  minReplicas: {{ .Values.replications.minReplicasHPA }}
  maxReplicas: {{ .Values.replications.maxReplicasHPA }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
