apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.global.namespace }}
  name: {{ .Values.name }}-service
  labels:
    app: {{ .Values.appLabel }}
spec:
  type: ClusterIP  # Default and suitable for intra-cluster communication
  ports:
    - port: {{ .Values.exposePort }}
      targetPort: {{ .Values.exposePort }}
      protocol: TCP
  selector:
    app: {{ .Values.appLabel }}