# Generated by Django 5.0.4 on 2024-05-13 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'crm_certificate',
            },
        ),
        migrations.CreateModel(
            name='CRMCrossBorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'crm_cross_border',
            },
        ),
        migrations.CreateModel(
            name='CRMPreferredLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'crm_preferred_load',
            },
        ),
        migrations.CreateModel(
            name='PostalCodeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=2)),
                ('postal_code', models.CharField(max_length=20)),
                ('place_name', models.CharField(max_length=100)),
                ('admin_name1', models.CharField(max_length=100)),
                ('admin_code1', models.CharField(max_length=20)),
                ('admin_name2', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_code2', models.CharField(blank=True, max_length=20, null=True)),
                ('admin_name3', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_code3', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('accuracy', models.IntegerField(blank=True, null=True)),
                ('coordinates', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Postal Code Information',
                'verbose_name_plural': 'Postal Codes Information',
                'db_table': 'crm_dic_postal_code_info',
            },
        ),
        migrations.CreateModel(
            name='CRMTrucks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opened', models.BooleanField(blank=True, null=True)),
                ('status', models.CharField(default='New', max_length=255)),
                ('number', models.CharField(blank=True, max_length=255, null=True)),
                ('license_plate', models.CharField(blank=True, max_length=255, null=True)),
                ('license_state', models.CharField(blank=True, max_length=255, null=True)),
                ('vincode', models.CharField(blank=True, max_length=255, null=True)),
                ('make', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('truck_type', models.CharField(blank=True, max_length=255, null=True)),
                ('trailer_type', models.CharField(blank=True, max_length=255, null=True)),
                ('door_type', models.CharField(blank=True, max_length=255, null=True)),
                ('is_reefer', models.BooleanField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, null=True)),
                ('company_signs', models.BooleanField(blank=True, null=True)),
                ('is_owner_coordinator_responsible', models.BooleanField(blank=True, null=True)),
                ('responsible', models.CharField(blank=True, max_length=255, null=True)),
                ('current_travel_order_number', models.CharField(blank=True, max_length=255, null=True)),
                ('crm_id', models.IntegerField(blank=True, null=True)),
                ('registration_expiration', models.DateField(blank=True, null=True)),
                ('insurance_expiration', models.DateField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_trucks', to=settings.AUTH_USER_MODEL)),
                ('certificates', models.ManyToManyField(to='truck.crmcertificate')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_trucks', to=settings.AUTH_USER_MODEL)),
                ('cross_borders', models.ManyToManyField(to='truck.crmcrossborder')),
                ('hired_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('modify_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_trucks', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.crmcompanies')),
                ('preferred_loads', models.ManyToManyField(to='truck.crmpreferredload')),
            ],
            options={
                'db_table': 'crm_trucks',
            },
        ),
        migrations.CreateModel(
            name='CRMTruckNotes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_truck_notes', to=settings.AUTH_USER_MODEL)),
                ('modify_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_truck_notes', to=settings.AUTH_USER_MODEL)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truck.crmtrucks')),
            ],
            options={
                'db_table': 'crm_truck_notes',
            },
        ),
        migrations.CreateModel(
            name='CRMTruckLocations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_truck_locations', to=settings.AUTH_USER_MODEL)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truck.crmtrucks')),
            ],
            options={
                'db_table': 'crm_truck_locations',
            },
        ),
        migrations.CreateModel(
            name='CRMDimensions',
            fields=[
                ('dimensions_id', models.AutoField(primary_key=True, serialize=False)),
                ('door_dims_height', models.FloatField(blank=True, null=True)),
                ('inside_dims_width', models.FloatField(blank=True, null=True)),
                ('inside_dims_height', models.FloatField(blank=True, null=True)),
                ('inside_dims_length', models.FloatField(blank=True, null=True)),
                ('valid_dims_width', models.FloatField(blank=True, null=True)),
                ('valid_dims_height', models.FloatField(blank=True, null=True)),
                ('valid_dims_length', models.FloatField(blank=True, null=True)),
                ('dims_units', models.CharField(blank=True, max_length=50, null=True)),
                ('payload', models.FloatField(blank=True, null=True)),
                ('payload_units', models.CharField(blank=True, max_length=50, null=True)),
                ('door_dims_width', models.FloatField(blank=True, null=True)),
                ('truck', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='truck.crmtrucks')),
            ],
            options={
                'db_table': 'crm_dimensions',
            },
        ),
    ]
